# YAML for launching the orderer
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spacex-peer
  labels:
    app: spacex-peer
spec:
  serviceName: spacex-peer
  replicas: 1
  selector:
    matchLabels:
      app: spacex-peer
  template:
    metadata:
      labels:
        app: spacex-peer
    spec:
      containers:
      - name: spacex-peer
        # image used
        image: acloudfan/k8s-hlf-spacex-peer:2.0
        # Uncomment the following during development/testing of the image
        # imagePullPolicy: Always
        env:
          - name: FABRIC_CFG_PATH
            value: /var/hyperledger/config
          - name: FABRIC_LOGGING_SPEC
            value: INFO
          - name: ORDERER_ADDRESS
            value: acme-orderer-clusterip:30750
          - name: ORG_CONTEXT
            value: spacex
          - name: CORE_PEER_ADDRESS
          # value: spacex-peer-clusterip:30851
            value: localhost:30951
        volumeMounts:
        - name: spacex-peer-ledger
          mountPath: /var/ledger
        - name: dockersock
          mountPath: /var/run/docker.sock
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
  volumeClaimTemplates:
  - metadata: 
      name: spacex-peer-ledger
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: general
      resources:
        requests:
          storage: 1Gi



---
# Expose the port 30851 as ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: spacex-peer-clusterip

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: spacex-peer

  ports:
    - name: spacex-peer-clusterip
      port: 30951
    # - name: spacex-peer-cc-clusterip
    #   port: 30852

  type: ClusterIP

---
# Expose the port 30851 as node port -  NEEDED if you
# are interested in connecting to the Pods from the Host
# machine - keep in mind you would need the IP for the node
# port service
apiVersion: v1
kind: Service
metadata:
  name: spacex-peer-nodeport

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: spacex-peer

  ports:
    - name: spacex-peer-nodeport-951
      port: 30951
      nodePort: 30951
    - name: spacex-peer-cc-nodeport-952
      port: 30952
      nodePort: 30952

  type: NodePort